rvm:
- 2.1.0
env:
  global:
  - secure: WFJvdvp6QT8NetNgE+Lo4TvhhMu2Z+PMdkbAyrnli7R8KjZBCDNbZ2fKulF9u1TicBOYOrxm8Exhh3pBPqiVlFezzV0MnpDHJSHfDYJAYUk+4ka7ldY5QWCFuTG1G2JKAQVUU9UfJSfubh/+pNAN3U2mhZKzhd4eF8eBywTMmcA=
  - secure: FFMvqlutlAV7IRg4sVL9C9XlBhLeVOi3NFqeAZ9eZqdmJ0ipLdwSzPsjnbUV0SXIOECaSUWtHO7YJUwC5wTBPwIDeq9hVPPojRJLbxti23O0xwCVJNYyWjzhcoamMs6QFzf0siiSae3/+CRgXhuts5o6L0UGVe123IJJKx+VuGU=
  - secure: No8n0UKivKMLSq1Xz9rNSW6L79jTMWgI0sUOxJpLy62v9iQFEb3FKtaTPduXs5PuorX0t2eA4Hlq/QCJSvX/nA/+qa42Lil0I6ARsyPDawGbO1l4EZ4GPamKtjRfyNlhBm0zB+PtSJXlQyAFc+xlVQa1vHOqLTfNRGfJb+SuGhc=
  - secure: Rf9HSGmItO8AkJkLCp9vWyfr0JXDiTYirtruojw1GWY7GDK29f3K/F0JFBhypoV1baGGNYGlDqf3Bkw8l//qguKkTbkUJ/Gxtrgxegv+xF7qSTPUgAG6jcXS1MBX8gNtDQSiwmbUkI3tHalH1kJTMQ+y+0Uhb2YCxBmIPtOgX3c=
  - secure: QFGYIjCLnHqtL+ABvFOdLGmtkwqm8kjEJV3G+arE2+BMgK3OutcuKWZm5aep7CxCsLJ22rI5huXQqDMejKZNVHacv5K3ytt8ukD86CePVh0ECuA5+xIs6HcL4SKvTJeVJhnc04xi9CTzhOmSR6njUmAPj2HV5piMkQ/8jfv+cPA=
  matrix:
  - DB: postgresql
before_script:
- psql -c "create database $DB_NAME;" -U $DB_USER
- RAILS_ENV=test bundle exec rake db:migrate
script:
- bundle exec rspec spec/
after_success:
- gem install heroku
- git remote add heroku $HEROKU_GIT_URL
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- heroku keys:clear
- yes | heroku keys:add
- yes | git push heroku master
