rvm:
- 2.1.0
env:
  global:
  - secure: jRqDDdCGFMcBuM1hdQi3vunUY6SPL5breqKs3NNfTxEfGMsH2QGAlwY4v2WRLBXAH11OeF1A/AzMFuVjbq08EUIS7Mwc19MjxhqRqVrSmL3WOrblYfwzLcPVF0PLPnkhFG8/EJj3tNhUSb5Hp55YSLKoRx7JrrBLp2x4+IAE5qg=
  - secure: VpYADZVz3iNJlrx79gGjboT9caRev9H+air7vnzD0pBsE2uKreNxdsaZA60X6XcMo9lLtu3R/OYfzjkfVhbvkSEimKziYo3vDj1DlJI9xrETov+wMPu1KIGeKPbawktXFgg3rFoTKf6Dynkcb/uiaG7EoYnlGEukB+e5AVcSDC0=
  matrix:
  - DB: postgresql
before_script:
- psql -c "create database webcal_test;" -U postgres
- RAILS_ENV=test bundle exec rake db:migrate
script:
- bundle exec rspec spec/
deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  run: RAILS_ENV=production rake db:migrate
  app:
    master: webcal-staging
    production: webcal
notifications:
  hipchat:
    rooms:
      secure: GVNlirt1qkVHo+RAvRSJPjUhm/Msa7bGeP9tqdl0L5woyZ/fRCqhSjN9EIyumK5PuIR9+2t1rzCbeEOoCAX1hz+SKmC/SvaNk5X1WX4fs0bL3KO3V96ME1AIEYxJ56Fs8z8+GGD/ONo9C5ZVpNmJlrUyxOxmBHS9boe0tQzi+qY=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} Build details: %{build_url}'
